### ISSUE TITLE
Work with Ignite 2 default app

### ISSUE THREAD

**Issue by quasor** [callstack-io/haul#113]
Using https://github.com/infinitered/ignite
```
ignite new project
cd project
yarn add --dev haul-cli
yarn run haul init
yarn run haul start -- --platform ios
```
Observe:
```
ERROR in ./App/Themes/Images.js
Module not found: Error: Can't resolve '../Images/button-bg.png' in '/Users/andrew/src/project/App/Themes'
 @ ./App/Themes/Images.js 11:17-51
 @ ./App/Themes/index.js
 @ ./App/Containers/Styles/RootContainerStyles.js
 @ ./App/Containers/RootContainer.js
 @ ./App/Containers/App.js
 @ ./index.ios.js
 @ multi ./~/haul-cli/src/utils/polyfillEnvironment.js ./index.ios.js

ERROR in ./App/Themes/Images.js
Module not found: Error: Can't resolve '../Images/Icons/icon-api-testing.png' in '/Users/andrew/src/project/App/Themes'
 @ ./App/Themes/Images.js 12:4-51
 @ ./App/Themes/index.js
 @ ./App/Containers/Styles/RootContainerStyles.js
 @ ./App/Containers/RootContainer.js
 @ ./App/Containers/App.js
 @ ./index.ios.js
 @ multi ./~/haul-cli/src/utils/polyfillEnvironment.js ./index.ios.js
```

| software         | version
| ---------------- | -------
| Haul             |  0.4.1
| react-native     |  0.4.2
| node             | 7.8
| yarn      | 0.21.3

**Comment by satya164** [comment]
Can you link to a demo project please?

**Comment by grabbou** [comment]
Alternatively, `ls` in `Images/Icons` folder.

**Comment by grabbou** [comment]
After debugging this for a while, it looks like it's because of Ignite shipping only with `button-bg@2x.png` file whereas our plugin requires the base resolution to be on the filesystem as well (eg.`button-bg.png` or `button-bg@1x.png`). It's probably worth figuring out how's Packager handling those cases and tweak.

One of the solutions would be to take lowest resolution from available files (e.g. if `@2x` is the only one, take it instead of throwing).
