### ISSUE TITLE
Haul + Reactotron without debugger

### ISSUE THREAD

**Issue by ferrannp** [callstack-io/haul#125]
### Current Behavior
[Reactotron](https://github.com/infinitered/reactotron) only connects / show messages when the debugger is active.

### Expected Behavior
I'd be nice to get Reactotron to work without having to activate the debugger (it works with the packager).

### Haul Configuration (webpack.haul.js)
```js
module.exports = ({ platform }) => ({
  entry: `./index.${platform}.js`,
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  0.5.0
| react-native     |  0.43.0
| node             |  6.3.1
| npm or yarn      | yarn@0.21.3

**Comment by skellock** [comment]
Dibs.  Will let you know what I find.

**Comment by skellock** [comment]
I'm having a hard time reproducing this.  I tried `haul-cli@1.2.0`, `haul-cli@1.5.0`, and `haul@master`.  Also tried `react-native@0.42.3` and `react-native@0.43.3`.  I haven't tested `react-native@0.43.0` as there were some issues with that release.  I'm running `node@7.6.0` (though I can't see that as a problem).

I'm using the `demo-react-native` sample app in reactotron as my test environment (has the same webpack.haul.js as yours).

I don't think haul is the problem here.  Would you be ok with closing this issue, spinning up a minimal repro and taking this to an issue over on Reactotron?  

I'd be also cool working through this with you on Slack too.  I'm curious where this is going off the rails.  In my experience with incompatibilities like this, 10 out of 10 times, it's usually something awful I'm doing on Reactotron.  ;P

**Comment by ferrannp** [comment]
Ok let's take it to Reactotron :D
