### ISSUE TITLE
Compile CLI instead of shipping with babel runtime

### ISSUE THREAD

**Issue by thymikee** [callstack-io/haul#203]
It's a feature

### Current Behavior
Haul CLI is shipping with `babel-register` compiling its code, therefore its boot time increases _a lot_

### Expected Behavior
We can compile CLI code to specified target (e.g. Node 4) with babel and get rid of the slow runtime.

cc @zamotany

**Comment by grabbou** [comment]
Unfortunately, that decision was a tradeoff we have made in order to transpile only required amount of code. That's why we use `babel-env` to detect what is supported and use it instead.

In reality, there's minimum amount of things we transpile on Node 6 and above - no need to include regenerator runtime etc.

**Comment by satya164** [comment]
Have you benchmarked it? I don't notice the startup to be slow.

**Comment by zamotany** [comment]
I do, especially if I have other programs in the background.

@grabbou 
If you're so worried about supporting ancient node versions, what about this:
- transpile for node 6 LTS
- if we detect earlier version -> babel-register with `preset-env`
??

**Comment by thymikee** [comment]
Displaying `--help`:

* with `babel-register`: `1.46s`.
* without it: `0.85s`

**Comment by satya164** [comment]
If we transpile anyway, it'll be better to transpile for everything instead of 2 different ways.

**Comment by grabbou** [comment]
I would like to see numbers in order to be able to decide whether it's worth tradeoff at all. 

Again, what is the point of transpiling for Node 7/8 users? In reality, this should be less of an issue as we are upgrading our environments. Ideally, everyone should be on latest, here, we provide support just as a legacy.

**Comment by grabbou** [comment]
If its `0.6s`, maybe it makes more sense to see what transforms are taking long and remove them during build step - maybe it's for instance `flow` that takes 80% of it.

**Comment by zamotany** [comment]
W/o transpilation: 1616ms
W/ transpilation: 425ms

**Comment by grabbou** [comment]
Let's remove `flow` from `src` and see if using that code with `babel-register` is as slow.

**Comment by satya164** [comment]
@thymikee you transpiled using the `current` option for `babel-preset-env`, but if we transpile, we would probably use `node 4`. Can you try with `node 4` and post the results so we can make a more informed decision on what to do?

**Comment by grabbou** [comment]
I think it's been discussed on Slack that there are no differences at the end of the day? Going to close this one until we can reproduce constant slowness that is worth fixing.

**Comment by thymikee** [comment]
There is a difference, which gets marginal after `babel-register` cache gets warm. Nevertheless worth exploring in near future
